name: tests

on: [push, workflow_dispatch]

jobs:
    test-backend:
        runs-on: ubuntu-latest

        defaults:
          run:
            working-directory: ./server

        steps:
            - uses: actions/checkout@v4
            - name: Setup Go
              uses: actions/setup-go@v4
              with:
                go-version: 1.21.x
            - name: Install Go dependencies
              run: go install
            - name: Run Go server
              run: go run . &
            - run: sleep 10
            - name: Run tests
              run: go test .
            - name: Stop app
              run: pkill -f "go run ."
